[tool.black]
line-length = 120
include = '(\.pyi?|\.ipynb)$'
quiet = true

[tool.isort]
profile = "black"
src_paths = ['(\.pyi?|\.ipynb)$']
known_first_party = ["shared"]
line_length = 120
quiet = true

[tool.pylint.main]
recursive = true

[tool.pylint.format]
max-line-length = 120
disable = ["line-too-long"]
max-locals = 50
max-statements = 150
max-args = 7

[tool.pylint.reports]
score = false
