# https://github.com/yte-template-engine/yte/tree/main
__use_yte__: true
__definitions__:
  - |
    def inclusive_range_mult(start, stop, mult):
      result = []
      while start <= stop:
        result += [start]
        start *= mult
      return result

    def inclusive_range_add(start, stop, step):
      result = []
      while start <= stop:
        result += [round(start, 3)]
        start += step
      return result

RAPTOR_BINARY: /srv/data/seiler/hibf_benchmark/raptor
DISPLAY_LAYOUT_BINARY: /srv/data/seiler/hibf_benchmark/display_layout

FILENAMES_FILE: /srv/public/leonard/hibf_benchmarks/data/1024/1024.filenames
QUERY_FILE: /srv/public/leonard/hibf_benchmarks/data/1024/reads_e2_250/all.fastq

# All the parameters to run with raptor
PARAMS:
  ALPHA: [60.0 ,40.0, 20.0, 10.0, 5.0, 2.0, 1.5, 1.3, 1.0, 0.7, 0.5]
  T_MAX: ?sorted([192, 768, 8192] + inclusive_range_mult(64, 2048, 2))
  NUM_HASHES: ?inclusive_range_add(2, 15, 1)
  KMER_SIZE: ?inclusive_range_add(18, 32, 1)
  RELAXED_FPR: ?[0.05] + inclusive_range_add(0.1, 0.9, 0.1)
  MODE: [none, U, U+R] # [none, U, U+R]

# Neccessary data parameters to run raptor 
DATA_PARAMETERS:
  QUERY_ERRORS: 2

# Default parameters to run raptor
DEFAULT_PARAMS:
  ALPHA: 1.2
  T_MAX: 192
  NUM_HASHES: 2
  KMER_SIZE: 32
  R_FPR: 0.5
  M_FPR: 0.05
  MODE: U+R

# Number of threads to use per task, not for parallel execution
NUM_THREADS: 1
