#RAPTOR_BINARY: /srv/public/leonard/raptor/build/bin/raptor
RAPTOR_BINARY: /srv/data/seiler/hibf_benchmark/raptor

DISPLAY_LAYOUT_BINARY: /srv/data/seiler/hibf_benchmark/display_layout
FILENAMES_FILE: /srv/public/leonard/hibf_benchmarks/data/1024/1024.filenames
QUERY_FILE: /srv/public/leonard/hibf_benchmarks/data/1024/reads_e2_250/all.fastq
BUILD_DIR: /srv/public/leonard/hibf_benchmarks/build
PLOT_DIR: /srv/public/leonard/hibf_benchmarks/scripts

# PARAMS:
#   # ALPHA: [1.0]
#   ALPHA: [60.0 ,40.0, 20.0, 10.0, 5.0, 2.0, 1.5, 1.3, 1.0, 0.7, 0.5]
#   T_MAX: [64]
#   NUM_HASHES: [3]
#   KMER_SIZE: [30]
#   RELAXED_FPR: [0.3]
#   MODE: [none, U, U+R] # [none, U, U+R]

PARAMS:
  ALPHA: [60.0 ,40.0, 20.0, 10.0, 5.0, 2.0, 1.5, 1.3, 1.0, 0.7, 0.5]
  T_MAX: [64, 128, 192, 256, 512, 768, 1024, 2048, 8192]
  NUM_HASHES: [2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15]
  KMER_SIZE: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
  RELAXED_FPR: [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  MODE: [none, U, U+R] # [none, U, U+R]

DATA_PARAMETERS:
  QUERY_ERRORS: 2

DEFAULT_PARAMS:
  ALPHA: 1.2
  T_MAX: 192
  NUM_HASHES: 2
  KMER_SIZE: 32
  R_FPR: 0.5
  M_FPR: 0.05
  WINDOW_SIZE: 32
  MODE: [U+R]

NUM_THREADS: 1 # Number of threads to use per task, not for parallel execution

TIME_FORMAT:
  - "KEY"
  - "SUBKEY"
  - "wall_clock_time_in_seconds"
  - "determine_query_length_in_seconds"
  - "query_file_io_in_seconds"
  - "load_index_in_seconds"
  - "compute_minimiser_avg_in_seconds"
  - "query_ibf_avg_in_seconds"
  - "generate_results_avg_in_seconds"

SIZE_FORMAT:
  - "KEY"
  - "SUBKEY"
  - "LEVEL"
  - "BIT_SIZE"
  - "AVG_LOAD_FACTOR"

KEYS:
  - "alpha"
  - "hash"
  - "kmer"
  - "relaxed-fpr"
  - "none"
  - "U"
  - "U+R"

####################### PLOT PARAMETERS #######################

PLOT_THEME: '/srv/public/leonard/hibf_benchmarks/scripts/bokeh_plot/plot_theme.yaml'

KEYS_TITLES:
  - "alpha"
  - "hash"
  - "k-mer"
  - "relaxed-fpr"
  - "no U no R"
  - "U"
  - "U and R"

PLOT_TIME_FORMAT:
  - "SUBKEY"
  - "determine_query_length_in_seconds"
  - "query_file_io_in_seconds"
  - "load_index_in_seconds"
  - "compute_minimiser_avg_in_seconds"
  - "query_ibf_avg_in_seconds"
  - "generate_results_avg_in_seconds"

PLOT_TIME_NAMES:
  - "Determine query length"
  - "Queryfile IO"
  - "Load index"
  - "Compute minimizer (avg)"
  - "Query IBF (avg)"
  - "Generate results (avg)"

PLOT_SIZE_FORMAT:
  - "SUBKEY"
  - "LEVEL_0"
  - "LEVEL_1"
  - "LEVEL_2"
  - "LEVEL_3"

PLOT_SIZE_NAMES:
  - "Level 0"
  - "Level 1"
  - "Level 2"
  - "Level 3"
