#RAPTOR_BINARY: /srv/public/leonard/raptor/build/bin/raptor
RAPTOR_BINARY: /srv/data/seiler/hibf_benchmark/raptor

DISPLAY_LAYOUT_BINARY: /srv/data/seiler/hibf_benchmark/display_layout
FILENAMES_FILE: /srv/public/leonard/hibf_benchmarks/data/data_set/8192.filenames
QUERY_FILE: /srv/public/leonard/hibf_benchmarks/data/data_set/reads_e2_250/all.fastq
OUTPUT_DIR: /srv/public/leonard/hibf_benchmarks/output
OUTPUT_TIME_NAME: time
OUTPUT_SIZE_NAME: size

PARAMS:
  ALPHA: [1.0]
  T_MAX: [64]
  NUM_HASHES: []
  KMER_SIZE: []
  RELAXED_FPR: []

DATA_PARAMETERS:
  QUERY_ERRORS: 2
  QUERY_LENGTH: 250

DEFAULT_PARAMS:
  T_MAX: 192
  KMER_SIZE: 32
  NUM_HASHES: 2
  ALPHA: 1.2
  R_FPR: 0.5
  M_FPR: 0.05
  WINDOW_SIZE: 32

NUM_THREADS: 4


# PARAMS:
#   ALPHA: [60.0 ,40.0, 20.0, 10.0, 5.0, 2.0, 1.5, 1.3, 1.0, 0.7, 0.5]
#   T_MAX: [64, 128, 192, 256, 512, 768, 1024, 2048, 8192]
#   NUM_HASHES: [2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15]
#   KMER_SIZE: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
#   RELAXED_FPR: [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

# PARAMS:
#   ALPHA: [1.0, 0.7]
#   T_MAX: [64, 128]
#   NUM_HASHES: []
#   KMER_SIZE: []
#   RELAXED_FPR: []