name: Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: build-update-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build-html:
    name: HTML
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: pip install --requirement requirements.txt

      - name: Build HTML
        run: |
          python3 scripts/main.py
          cp build/index.html index.html

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: ./index.html
          author_name: seqan-actions[bot]
          author_email: seqan-actions@users.noreply.github.com
          message: '[MISC] Update HTML'
